language: python
python:
  - "2.7"
before_install:
  - "wget -O libgit2.tar.gz https://github.com/libgit2/libgit2/archive/v0.19.0.tar.gz"
  - "tar xf libgit2.tar.gz"
  - "cd libgit2-*"
  - "mkdir build && cd build"
  - "cmake .. && cmake --build ."
  - "sudo cmake --build . --target install"
  - "cd .."
  - "cd .. && rm -rf libgit2-*"
  - "export LIBGIT2='/usr/local'"
  - "export LDFLAGS=\"-Wl,-rpath='$LIBGIT2/lib',--enable-new-dtags $LDFLAGS\""
before_script:
  - "pip install --use-mirrors pep8 'pylint<1.0.0' Flask-Testing coverage nose coveralls"
  - "pip install --use-mirrors filemagic"
  - "git fetch --unshallow || true"
  - "git fetch --all"
  - "git branch ambiguous 1f51b91ac383806df9d322ae67bbad3364f50811"
  - "git branch -v"
  - "git checkout -b master || true"
script:
  - "pep8 restfulgit"
  - "pylint --rcfile=pylint.rc restfulgit"
  - "nosetests --with-xunit --failure-detail"
  - "PYTHONPATH=. coverage run tests/test_restfulgit.py"
after_success:
  - coveralls
